### ISSUE TITLE
Plugin installation error

### ISSUE THREAD

**Issue by aboobolaky** [elastic/timelion#109]
Hi,
i'm trying to install Timelion and i'm getting the following error

Installing timelion
Attempting to transfer from https://download.elastic.co/kibana/timelion/timelion-latest.tar.gz
Transferring 3522921 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in ../installedPlugins/timelion/public/app.js
    Module build failed: SyntaxError: /opt/kibana/installedPlugins/timelion/public/app.js: Unexpected token (3:0)
      1 | var _ = require('lodash');
      2 | var logoUrl = require('./logo.png');
    > 3 | <<<<<<< HEAD
        | ^
      4 | =======
      5 | var configFile = require('../timelion.json');
      6 | var moment = require('moment-timezone');
        at Parser.pp.raise (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
        at Parser.pp.unexpected (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:82:8)
        at Parser.pp.parseExprAtom (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:425:12)
        at Parser.pp.parseExprSubscripts (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:236:19)
        at Parser.pp.parseMaybeUnary (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:217:19)
        at Parser.pp.parseExprOps (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:163:19)
        at Parser.pp.parseMaybeConditional (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:145:1            9)
        at Parser.pp.parseMaybeAssign (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:112:19)
        at Parser.pp.parseExpression (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:79:19)
        at Parser.pp.parseStatement (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:137:23)
        at Parser.pp.parseTopLevel (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:30:21)
        at Parser.parse (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/parser/index.js:70:17)
        at Object.parse (/opt/kibana/node_modules/babel-core/node_modules/babylon/lib/index.js:45:50)
        at Object.exports.default (/opt/kibana/node_modules/babel-core/lib/helpers/parse.js:36:18)
        at File.parse (/opt/kibana/node_modules/babel-core/lib/transformation/file/index.js:574:40)
        at File.parseCode (/opt/kibana/node_modules/babel-core/lib/transformation/file/index.js:691:20)
     @ ../optimize/bundles/timelion.entry.js 24:0-31
"

Im using ES 2.3.2, Kib 4.5.0

Any ideas?

**Comment by cmac458** [comment]
There was a merge comment accidently committed seems to be gone now but not updated in the latest tar.gz file. I had to pull down the latest release tar, unzip, remove the comments, zip and install the new file. Until the release jar is updated that's the easiest way to get round it.

**Comment by aboobolaky** [comment]
thanks for heads up :)

**Comment by mverma-va** [comment]
Please update once this issue is fixed in the latest tar.gz?

**Comment by regit** [comment]
Label critical maybe as it breaks everything ?

**Comment by rashidkpc** [comment]
Welp, I really screwed that one up. fixed now:

```
$ ./bin/kibana plugin -i elastic/timelion
Installing timelion
Attempting to transfer from https://download.elastic.co/elastic/timelion/timelion-latest.tar.gz
Transferring 3521038 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
```

**Comment by mansunkuo** [comment]
I just ran into the same error but the error message is slightly different:

```
root@elk:/opt/kibana/installedPlugins# /opt/kibana/bin/kibana plugin -i elastic/timelion
Installing timelion
Attempting to transfer from https://download.elastic.co/elastic/timelion/timelion-latest.tar.gz
Transferring 3780050 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Optimizations failure.

    ERROR in ./timelion/public/app.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /opt/kibana/installedPlugins/timelion/public/directives/scroll_class in /opt/kibana/installedPlugins/timelion/public
     @ ./timelion/public/app.js 12:0-51
"
```

Do I miss anything?

**Comment by carioka88** [comment]
I think it is related to the file **.babelcache.json** in **/opt/kibana/optimize**
In my case it was: **-rw-r--r--.  1 root root .babelcache.json**
Then I change it to: **-rw-r--r--.  1 kibana root .babelcache.json**
And it is working now... I don't know if it is the same for you..

**Comment by Opticsponge** [comment]
@mansunkuo I am seeing same issue changing owner .babelcache.json didn't help I will try and install from downloaded file next

**Comment by jd-carroll** [comment]
@rashidkpc Can you please check this again, I am also seeing the same [issue](https://discuss.elastic.co/t/timelion-plugin-installation/51232).
