### ISSUE TITLE
query_parsing_exception with geo_bunding_box

### ISSUE THREAD

**Issue by apenen** [elastic/timelion#125]
Hi.

When I apply a geo_bunding_box in kibana dashboard, appears and error and timeseries visualization doesn't draw.

Error:  in cell #1: [query_parsing_exception] [_na] query malformed, must start with start_object, with: {"index":"logstash-2016.05.14","line":1,"col":122} (and) [query_parsing_exception] [_na] query malformed, must start with start_object, with: {"index":"logstash-2016.05.15","line":1,"col":122} (and) [query_parsing_exception] [_na] query malformed, must start with start_object, with: {"index":"logstash-2016.05.16","line":1,"col":122} (and) [query_parsing_exception] [_na] query malformed, must start with start_object, with: {"index":"logstash-2016.05.17","line":1,"col":122} (and) [query_parsing_exception] [_na] query malformed, must start with start_object, with: {"index":"logstash-2016.05.18","line":1,"col":122} (and) [query_parsing_exception] [_na] query malformed, must start with start_object, with: {"index":"logstash-2016.05.19","line":1,"col":122}
    at throwWithCell (/opt/kibana/installedPlugins/marvel/server/handlers/chain_runner.js:28:11)
    at /opt/kibana/installedPlugins/marvel/server/handlers/chain_runner.js:152:13
    at arrayEach (/opt/kibana/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/opt/kibana/node_modules/lodash/index.js:3345:13)
    at /opt/kibana/installedPlugins/marvel/server/handlers/chain_runner.js:144:9
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/opt/kibana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/kibana/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/kibana/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/opt/kibana/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/opt/kibana/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/kibana/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/kibana/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

And this is my timelion expression:

.es(index='logstash-*',q='type:nginx-access',metric='sum:bytes').divide(1024).precision(0).label("Current kB").color(green), .es(index='logstash-*',q='type:nginx-access',offset='-1d',metric='sum:bytes').divide(1024).precision(0).label("-1D kB").color(lightgreen)

**Comment by rashidkpc** [comment]
Fixed and released: https://github.com/elastic/timelion/commit/bfc3e90a63556982537e495a372b94e442f0d46e

Reinstall to get it.
