### ISSUE TITLE
GET request to worldbank api returns ECONNREFUSED error response

### ISSUE THREAD

**Issue by bratwurzt** [elastic/timelion#135]
Calling .wbi(MZ) in timelion syntax returns stacktrace:
```
Error:  in cell #1: request to http://api.worldbank.org/countries/MZ/indicators/SP.POP.TOTL?date=2016:2016&format=json&per_page=1000 failed, reason: connect ECONNREFUSED 54.208.17.237:80
    at throwWithCell (/opt/kibana/installedPlugins/timelion/server/handlers/chain_runner.js:28:11)
    at /opt/kibana/installedPlugins/timelion/server/handlers/chain_runner.js:152:13
    at arrayEach (/opt/kibana/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/opt/kibana/node_modules/lodash/index.js:3345:13)
    at /opt/kibana/installedPlugins/timelion/server/handlers/chain_runner.js:144:9
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/opt/kibana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/kibana/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/kibana/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/opt/kibana/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/opt/kibana/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/kibana/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/kibana/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
Where provided IP in stacktrace is from amazon, not mine - I can call:
http://api.worldbank.org/countries/MZ/indicators/SP.POP.TOTL?date=2016:2016&format=json&per_page=1000
locally just fine.

**Comment by rashidkpc** [comment]
ECONNREFUSED Is ECONNREFUSED. There's not much timelion could do to fake this error. It's possible, likely even, that the actual API servers are behind a balanced or being dns round robined and one of them is down. Try the actual IP in the error.

**Comment by bratwurzt** [comment]
I understand the meaning of ECONNREFUSED and am not insinuating that timelion faked the error - why would I? What I don't understand is when I call the same URL with curl GET from the same server where kibana is deployed, I get no such error.

**Comment by rashidkpc** [comment]
Sounds like a fluke to me, I also can't imagine a reason this would occur
