### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by michbsd** [elastic/timelion#141]
Hi, 

Just installed timelion plugin with kibana 4.5 - installation worked fine.
However when I run through the first-run help wizard, I get an error: 

Timelion: Error: in cell #1: [reduce_search_phase_exception] [reduce]

Error:  in cell #1: [reduce_search_phase_exception] [reduce] 
    at throwWithCell (/usr/local/www/kibana45/installedPlugins/timelion/server/handlers/chain_runner.js:28:11)
    at /usr/local/www/kibana45/installedPlugins/timelion/server/handlers/chain_runner.js:152:13
    at arrayEach (/usr/local/www/kibana45/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/local/www/kibana45/node_modules/lodash/index.js:3345:13)
    at /usr/local/www/kibana45/installedPlugins/timelion/server/handlers/chain_runner.js:144:9
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at tryCatcher (/usr/local/www/kibana45/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/www/kibana45/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/local/www/kibana45/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/local/www/kibana45/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/local/www/kibana45/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/www/kibana45/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/www/kibana45/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by michbsd** [comment]
*ping*

**Comment by rashidkpc** [comment]
If I had to guess, its this: https://github.com/elastic/elasticsearch/issues/11340

**Comment by michbsd** [comment]
I am running ES 2.3.0  - so I do not think this applies.

**Comment by rashidkpc** [comment]
Really not sure whats going on here, maybe Elasticsearch running out of memory? This isn't an timelion error, its an exception coming up from Elasticsearch

**Comment by michbsd** [comment]
Non MEM issues

**Comment by michbsd** [comment]
This is solved. The FreeBSD port does not install the lang-expression / lang-groovy modules. So obviously it will not work.

I have reported the issue to port maintainer, and installed them manually. Everything works.
