### ISSUE TITLE
problem with timelion.

### ISSUE THREAD

**Issue by pill663** [elastic/timelion#172]
I use my own kibana version 4.5.4 to bind with aws es 2.3.
kibana works fine. 
But when I install the timelion plugin for my kibana, then the timelion didn't work.
shows this error in webpage:
Error: in cell #1: [reduce_search_phase_exception] [reduce] 
at throwWithCell (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/installedPlugins/timelion/server/handlers/chain_runner.js:29:11)
at /opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/installedPlugins/timelion/server/handlers/chain_runner.js:156:13
at arrayEach (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/node_modules/lodash/index.js:1289:13)
at Function. (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/node_modules/lodash/index.js:3345:13)
at /opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/installedPlugins/timelion/server/handlers/chain_runner.js:148:9
at bound (domain.js:287:14)
at runBound (domain.js:300:12)
at tryCatcher (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/node_modules/bluebird/js/main/util.js:26:23)
at Promise.settlePromiseFromHandler (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/nodemodules/bluebird/js/main/promise.js:503:31)
at Promise.settlePromiseAt (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/nodemodules/bluebird/js/main/promise.js:577:18)
at Promise.settlePromises (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/nodemodules/bluebird/js/main/promise.js:693:14)
at Async.drainQueue (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/nodemodules/bluebird/js/main/async.js:123:16)
at Async.drainQueues (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/nodemodules/bluebird/js/main/async.js:133:10)
at Immediate.Async.drainQueues as _onImmediate
at processImmediate as _immediateCallback

I don't know whether it's a problem with kibana or es.

**Comment by tylersmalley** [comment]
@rashidkpc, I was able the replicate the issue of installing Kibana `4.5.4` and getting a white screen for Timelion. Pulling down `timelion-latest.tar.gz` I see the version is `0.1.168`. That version  was from back in November, did it get overwritten some how?

**Comment by rashidkpc** [comment]
Well that's just weird. Maybe something happened with S3? I can’t imagine how 168 would’ve been published as latest. In any case I’ve just republished 0.1.402 and tested it, seems to be fine.
