### ISSUE TITLE
problem with timelion, still exists.

### ISSUE THREAD

**Issue by pill663** [elastic/timelion#176]
refer to: https://github.com/elastic/timelion/issues/172

I use my own kibana version 4.5.4 to bind with aws es 2.3.
kibana works fine. 
But when I install the timelion plugin for my kibana, then the timelion didn't work.
shows this error in webpage:
Error: in cell #1: [reduce_search_phase_exception] [reduce] 
at throwWithCell (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/installedPlugins/timelion/server/handlers/chain_runner.js:29:11)
at /opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/installedPlugins/timelion/server/handlers/chain_runner.js:156:13
at arrayEach (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/node_modules/lodash/index.js:1289:13)
at Function. (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/node_modules/lodash/index.js:3345:13)
at /opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/installedPlugins/timelion/server/handlers/chain_runner.js:148:9
at bound (domain.js:287:14)
at runBound (domain.js:300:12)
at tryCatcher (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/node_modules/bluebird/js/main/util.js:26:23)
at Promise.settlePromiseFromHandler (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/nodemodules/bluebird/js/main/promise.js:503:31)
at Promise.settlePromiseAt (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/nodemodules/bluebird/js/main/promise.js:577:18)
at Promise.settlePromises (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/nodemodules/bluebird/js/main/promise.js:693:14)
at Async.drainQueue (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/nodemodules/bluebird/js/main/async.js:123:16)
at Async.drainQueues (/opt/mateinfo/maintenance/kibana-4.5.4-linux-x64/nodemodules/bluebird/js/main/async.js:133:10)
at Immediate.Async.drainQueues as _onImmediate
at processImmediate as _immediateCallback

I don't know whether it's a problem with kibana or es.
As the previous issue said, the timelion version was updated. I've reinstall the timelion plugin, the error still exists.
I'm thinking it maybe a problem with aws es.
so I reached out to aws support, they said: "Timelion needs lang-groovy and lang-expression enabled as Elasticsearch module, and our version of ES does not support this".
I don't understand what does it mean, aws es version is 2.3, what is lang-groovy and lang-expression?

**Comment by rashidkpc** [comment]
This isn't a timelion bug, this is an AWS issue. For whatever reason, AWS disables Lucene expressions. Timelion works with Elasticsearch as it ships by default, which is with Lucene expressions enabled.

https://github.com/elastic/timelion/blob/0d6c3c877af1d7581a6adb8ff5357a05563ed012/server/series_functions/es/lib/create_date_agg.js#L29
