### ISSUE TITLE
Error trying to access wbi data

### ISSUE THREAD

**Issue by thoughtcroft** [elastic/timelion#39]
I am running timelion in a kibana docker container and get the following when I try to enter ".wbi(US,indicator=IP.PAT.RESD)" in the console I get the following error:

Timelion: Error: in cell #1: Worldbank request succeeded, but there was no data for countries/US/indicators/IP.PAT.RESD

And extra info:

````Error:  in cell #1: Worldbank request succeeded, but there was no data for countries/US/indicators/IP.PAT.RESD
    at throwWithCell (/opt/kibana/installedPlugins/timelion/handlers/chain_runner.js:28:9)
    at /opt/kibana/installedPlugins/timelion/handlers/chain_runner.js:146:11
    at arrayEach (/opt/kibana/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/opt/kibana/node_modules/lodash/index.js:3345:13)
    at /opt/kibana/installedPlugins/timelion/handlers/chain_runner.js:138:7
    at bound (domain.js:254:14)
    at runBound (domain.js:267:12)
    at tryCatcher (/opt/kibana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/opt/kibana/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/opt/kibana/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/opt/kibana/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/opt/kibana/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/opt/kibana/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/opt/kibana/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)````

Any ideas about what is happening here? How do I find out what is happening?

**Comment by thoughtcroft** [comment]
Actually, there was no data for the period I specified. Doofus!
