### ISSUE TITLE
Passing dashboard filters to timeseries charts

### ISSUE THREAD

**Issue by koszti** [elastic/timelion#80]
Would be nice to pass the applied filters from the Kibana dashboard to the new Timeseries charts so that it would search and analyse only the filtered data. At the moment only the time filter changes are passing to the new Timeseries charts.

Maybe an optional token might work in the Timelion expression which evaluates at runtime (?). E.g.:
.es(@kibanafilter, metric=sum:purchases)

(..where @kibanafilter is the filter string that is applied on the dashboard)

**Comment by rashidkpc** [comment]
I'd like to do this, I'd probably add another parameter to the .es() function, something like `.es(metric=sum:purchase, filters=true)`

**Comment by smjgithub** [comment]
+1

**Comment by alain2208** [comment]
thanks works nice now

**Comment by SKumarMN** [comment]
is this Fix available in Kibana 5.3?

**Comment by SKumarMN** [comment]
I get the below errors when i use filters 

es expression is as below
.es(index=test,metric='avg:udf_nn',filters=true).label('Current')


Error
Timelion: Error: Unknown argument to es: filters

 Less Info
OK
Error: Unknown argument to es: filters
    at /usr/share/kibana/src/core_plugins/timelion/server/handlers/lib/reposition_arguments.js:43:24
    at arrayEach (/usr/share/kibana/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/share/kibana/node_modules/lodash/index.js:3345:13)
    at repositionArguments (/usr/share/kibana/src/core_plugins/timelion/server/handlers/lib/reposition_arguments.js:9:5)
    at invoke (/usr/share/kibana/src/core_plugins/timelion/server/handlers/chain_runner.js:82:12)
    at /usr/share/kibana/src/core_plugins/timelion/server/handlers/chain_runner.js:145:14
    at arrayMap (/usr/share/kibana/node_modules/lodash/index.js:1406:25)
    at map (/usr/share/kibana/node_modules/lodash/index.js:6710:14)
    at interceptor (/usr/share/kibana/node_modules/lodash/index.js:12240:26)
    at thru (/usr/share/kibana/node_modules/lodash/index.js:5927:26)
    at baseWrapperValue (/usr/share/kibana/node_modules/lodash/index.js:2768:30)
    at LazyWrapper.lazyValue [as value] (/usr/share/kibana/node_modules/lodash/index.js:1077:16)
    at baseWrapperValue (/usr/share/kibana/node_modules/lodash/index.js:2761:25)
    at LodashWrapper.wrapperValue (/usr/share/kibana/node_modules/lodash/index.js:6124:14)
    at preProcessSheet (/usr/share/kibana/src/core_plugins/timelion/server/handlers/chain_runner.js:146:8)
    at Object.processRequest (/usr/share/kibana/src/core_plugins/timelion/server/handlers/chain_runner.js:190:12)
